package com.example.william.myapplication;

import java.util.ArrayList;

public class CountryArray {
    public static Country[] populateCountry(){
        ArrayList<Country> c = new ArrayList<>();

        c.add(new Country(1,"Afghanistan"));
        c.add(new Country(2,"Albania"));
        c.add(new Country(3,"Algeria"));
        c.add(new Country(4,"American Samoa"));
        c.add(new Country(5,"Andorra"));
        c.add(new Country(6,"Angola"));
        c.add(new Country(7,"Anguilla"));
        c.add(new Country(8,"Antarctica"));
        c.add(new Country(9,"Antigua and Barbuda"));
        c.add(new Country(10,"Argentina"));
        c.add(new Country(11,"Armenia"));
        c.add(new Country(12,"Aruba"));
        c.add(new Country(13,"Australia"));
        c.add(new Country(14,"Austria"));
        c.add(new Country(15,"Azerbaijan"));
        c.add(new Country(16,"Bahamas"));
        c.add(new Country(17,"Bahrain"));
        c.add(new Country(18,"Bangladesh"));
        c.add(new Country(19,"Barbados"));
        c.add(new Country(20,"Belarus"));
        c.add(new Country(21,"Belgium"));
        c.add(new Country(22,"Belize"));
        c.add(new Country(23,"Benin"));
        c.add(new Country(24,"Bermuda"));
        c.add(new Country(25,"Bhutan"));
        c.add(new Country(26,"Bolivia"));
        c.add(new Country(27,"Bosnia Hercegovina"));
        c.add(new Country(28,"Botswana"));
        c.add(new Country(29,"Bouvet Island"));
        c.add(new Country(30,"Brazil"));
        c.add(new Country(31,"British Indian Ocean Territory"));
        c.add(new Country(32,"Brunei Darussalam"));
        c.add(new Country(33,"Bulgaria"));
        c.add(new Country(34,"Burkina Faso"));
        c.add(new Country(35,"Burundi"));
        c.add(new Country(36,"Cambodia"));
        c.add(new Country(37,"Cameroon"));
        c.add(new Country(38,"Canada"));
        c.add(new Country(39,"Cape Verde"));
        c.add(new Country(40,"Cayman Islands"));
        c.add(new Country(41,"Central African Republic"));
        c.add(new Country(42,"Chad"));
        c.add(new Country(43,"Chile"));
        c.add(new Country(44,"China"));
        c.add(new Country(45,"Christmas Island"));
        c.add(new Country(46,"Cocos (Keeling) Islands"));
        c.add(new Country(47,"Colombia"));
        c.add(new Country(48,"Comoros"));
        c.add(new Country(49,"Congo"));
        c.add(new Country(50,"Cook Islands"));
        c.add(new Country(51,"Costa Rica"));
        c.add(new Country(52,"Cote D'ivoire"));
        c.add(new Country(53,"Croatia"));
        c.add(new Country(54,"Cuba"));
        c.add(new Country(55,"Cyprus"));
        c.add(new Country(56,"Czech Republic"));
        c.add(new Country(57,"Czechoslovakia"));
        c.add(new Country(58,"Denmark"));
        c.add(new Country(59,"Djibouti"));
        c.add(new Country(60,"Dominica"));
        c.add(new Country(61,"Dominican Republic"));
        c.add(new Country(62,"East Timor"));
        c.add(new Country(63,"Ecuador"));
        c.add(new Country(64,"Egypt"));
        c.add(new Country(65,"El Salvador"));
        c.add(new Country(66,"Equatorial Guinea"));
        c.add(new Country(67,"Estonia"));
        c.add(new Country(68,"Ethiopia"));
        c.add(new Country(69,"Falkland Islands (Malvinas)"));
        c.add(new Country(70,"Faroe Islands"));
        c.add(new Country(71,"Fiji"));
        c.add(new Country(72,"Finland"));
        c.add(new Country(73,"France"));
        c.add(new Country(74,"French Guiana"));
        c.add(new Country(75,"French Polynesia"));
        c.add(new Country(76,"French Southern Territories"));
        c.add(new Country(77,"Gabon"));
        c.add(new Country(78,"Gambia"));
        c.add(new Country(79,"Georgia"));
        c.add(new Country(80,"Germany"));
        c.add(new Country(81,"Ghana"));
        c.add(new Country(82,"Gibraltar"));
        c.add(new Country(83,"Greece"));
        c.add(new Country(84,"Greenland"));
        c.add(new Country(85,"Grenada"));
        c.add(new Country(86,"Guadeloupe"));
        c.add(new Country(87,"Guam"));
        c.add(new Country(88,"Guatemala"));
        c.add(new Country(89,"Guinea"));
        c.add(new Country(90,"Guinea-Bissau"));
        c.add(new Country(91,"Guyana"));
        c.add(new Country(92,"Haiti"));
        c.add(new Country(93,"Heard and Mc Donald Islands"));
        c.add(new Country(94,"Honduras"));
        c.add(new Country(95,"Hong Kong"));
        c.add(new Country(96,"Hungary"));
        c.add(new Country(97,"Iceland"));
        c.add(new Country(98,"India"));
        c.add(new Country(99,"Indonesia"));
        c.add(new Country(100,"Iran"));
        c.add(new Country(101,"Iraq"));
        c.add(new Country(102,"Ireland"));
        c.add(new Country(103,"Israel"));
        c.add(new Country(104,"Italy"));
        c.add(new Country(105,"Jamaica"));
        c.add(new Country(106,"Japan"));
        c.add(new Country(107,"Jordan"));
        c.add(new Country(108,"Kazakhstan"));
        c.add(new Country(109,"Kenya"));
        c.add(new Country(110,"Kiribati"));
        c.add(new Country(111,"Korea (North)"));
        c.add(new Country(112,"Korea (South)"));
        c.add(new Country(113,"Kuwait"));
        c.add(new Country(114,"Kyrgyzstan"));
        c.add(new Country(115,"Laos"));
        c.add(new Country(116,"Latvia"));
        c.add(new Country(117,"Lebanon"));
        c.add(new Country(118,"Lesotho"));
        c.add(new Country(119,"Liberia"));
        c.add(new Country(120,"Libyan Arab Jamahiriya"));
        c.add(new Country(121,"Liechtenstein"));
        c.add(new Country(122,"Lithuania"));
        c.add(new Country(123,"Luxembourg"));
        c.add(new Country(124,"Macau"));
        c.add(new Country(125,"Madagascar"));
        c.add(new Country(126,"Malawi"));
        c.add(new Country(127,"Malaysia"));
        c.add(new Country(128,"Maldives"));
        c.add(new Country(129,"Mali"));
        c.add(new Country(130,"Malta"));
        c.add(new Country(131,"Marshall Islands"));
        c.add(new Country(132,"Martinique"));
        c.add(new Country(133,"Mauritania"));
        c.add(new Country(134,"Mauritius"));
        c.add(new Country(135,"Mexico"));
        c.add(new Country(136,"Micronesia"));
        c.add(new Country(137,"Monaco"));
        c.add(new Country(138,"Mongolia"));
        c.add(new Country(139,"Montserrat"));
        c.add(new Country(140,"Morocco"));
        c.add(new Country(141,"Mozambique"));
        c.add(new Country(142,"Myanmar"));
        c.add(new Country(143,"Namibia"));
        c.add(new Country(144,"Nauru"));
        c.add(new Country(145,"Nepal"));
        c.add(new Country(146,"Netherlands"));
        c.add(new Country(147,"Netherlands Antilles"));
        c.add(new Country(149,"New Caledonia"));
        c.add(new Country(150,"New Zealand"));
        c.add(new Country(151,"Nicaragua"));
        c.add(new Country(152,"Niger"));
        c.add(new Country(153,"Nigeria"));
        c.add(new Country(154,"Niue"));
        c.add(new Country(155,"Norfolk Island"));
        c.add(new Country(156,"Northern Mariana Islands"));
        c.add(new Country(157,"Norway"));
        c.add(new Country(158,"Oman"));
        c.add(new Country(160,"Pakistan"));
        c.add(new Country(161,"Palau"));
        c.add(new Country(162,"Panama"));
        c.add(new Country(163,"Papua New Guinea"));
        c.add(new Country(164,"Paraguay"));
        c.add(new Country(165,"Peru"));
        c.add(new Country(166,"Philippines"));
        c.add(new Country(167,"Pitcairn"));
        c.add(new Country(168,"Poland"));
        c.add(new Country(169,"Portugal"));
        c.add(new Country(170,"Puerto Rico"));
        c.add(new Country(171,"Qatar"));
        c.add(new Country(172,"Republic Of Moldova"));
        c.add(new Country(173,"Reunion"));
        c.add(new Country(174,"Romania"));
        c.add(new Country(175,"Russia"));
        c.add(new Country(176,"Rwanda"));
        c.add(new Country(177,"Saint Kitts And Nevis"));
        c.add(new Country(178,"Saint Lucia"));
        c.add(new Country(179,"Saint Vincent and The Grenadines"));
        c.add(new Country(180,"Samoa"));
        c.add(new Country(181,"San Marino"));
        c.add(new Country(182,"Sao Tome and Principe"));
        c.add(new Country(183,"Saudi Arabia"));
        c.add(new Country(184,"Senegal"));
        c.add(new Country(185,"Seychelles"));
        c.add(new Country(186,"Sierra Leone"));
        c.add(new Country(187,"Singapore"));
        c.add(new Country(188,"Slovakia"));
        c.add(new Country(189,"Slovenia"));
        c.add(new Country(190,"Solomon Islands"));
        c.add(new Country(191,"Somalia"));
        c.add(new Country(192,"South Africa"));
        c.add(new Country(193,"Spain"));
        c.add(new Country(194,"Sri Lanka"));
        c.add(new Country(195,"St. Helena"));
        c.add(new Country(196,"St. Pierre and Miquelon"));
        c.add(new Country(197,"Sudan"));
        c.add(new Country(198,"Suriname"));
        c.add(new Country(199,"Svalbard and Jan Mayen Islands"));
        c.add(new Country(200,"Swaziland"));
        c.add(new Country(201,"Sweden"));
        c.add(new Country(202,"Switzerland"));
        c.add(new Country(203,"Syrian Arab Republic"));
        c.add(new Country(204,"Taiwan"));
        c.add(new Country(205,"Tajikistan"));
        c.add(new Country(206,"Tanzania"));
        c.add(new Country(207,"Thailand"));
        c.add(new Country(208,"Togo"));
        c.add(new Country(209,"Tokelau"));
        c.add(new Country(210,"Tonga"));
        c.add(new Country(211,"Trinidad and Tobago"));
        c.add(new Country(212,"Tunisia"));
        c.add(new Country(213,"Turkey"));
        c.add(new Country(214,"Turkmenistan"));
        c.add(new Country(215,"Turks and Caicos Islands"));
        c.add(new Country(216,"Tuvalu"));
        c.add(new Country(217,"Uganda"));
        c.add(new Country(218,"Ukraine"));
        c.add(new Country(219,"United Arab Emirates"));
        c.add(new Country(220,"United Kingdom"));
        c.add(new Country(221,"United States"));
        c.add(new Country(222,"United States Minor Outlying Islands"));
        c.add(new Country(223,"Uruguay"));
        c.add(new Country(225,"Uzbekistan"));
        c.add(new Country(226,"Vanuatu"));
        c.add(new Country(227,"Vatican City State (Holy See)"));
        c.add(new Country(228,"Venezuela"));
        c.add(new Country(229,"Vietnam"));
        c.add(new Country(230,"Virgin Islands (British)"));
        c.add(new Country(231,"Virgin Islands (U.S.)"));
        c.add(new Country(232,"Wallis and Futuna Islands"));
        c.add(new Country(233,"Western Sahara"));
        c.add(new Country(234,"Yemen"));
        c.add(new Country(235,"Yugoslavia"));
        c.add(new Country(236,"Zaire"));
        c.add(new Country(237,"Zambia"));
        c.add(new Country(238,"Zimbabwe"));
        c.add(new Country(239,"Macedonia"));

        return (Country[]) c.toArray();
    }
}
